apiVersion: v1
kind: PersistentVolume
metadata:
  name: ashis-task3
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/ashis/keycloak-k8"



