apiVersion: v1
kind: PersistentVolume
metadata:
  name: msssql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/ashis/keycloak-k8/"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: msssql-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: msssql-pv