apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  selector:
     matchLabels:
       app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_USER
          value: "ashu"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "vV5r9tn0M4@"
        - name: MSSQL_DB
          value: keycloak
        volumeMounts:
        - name: mssqldb
          mountPath: "/var/opt/mssqldb"
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: msssql-pvc