apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ashis-claims
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
  volumeName: ashis-tasks
